### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cricrio** [cricrio/my-awesome-website#1]
- [x] Start the site
- [ ] Add className to all the styled components https://www.viget.com/articles/inline-styles-user-style-sheets-and-accessibility/
- [ ] Add made with ... ...
- [ ] Automatic deploy with netlify
- [ ] Buy domain 
- [ ] Improve SEO
- [ ] Use animation for the job titles to improve accessibility
- [ ] Add description 
- [ ] Start the blog 
- [ ] Write: Hello World Article
- [ ] Write: The things I learned building this site
